---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-data.table=1.17.8
  - r-matrix=1.7_5
  - r-r.utils==2.13.0
