name: fastreadcounter
description: Count reads from BAM file into genomic ranges (GTF, BED, VCF) using FastReadCounter
keywords:
  - read counting
  - BAM
  - GTF
  - BED
  - VCF
  - quantification
tools:
  - fastreadcounter:
      description: |
        FastReadCounter is a Java-based tool for fast counting of reads
        from BAM files into genomic ranges (GTF, BED, VCF).
      homepage: https://github.com/DeplanckeLab/FastReadCounter
      licence: ["GPL-2.0-or-later"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - bam:
        type: file
        description: BAM file (does not need to be sorted or indexed)
        pattern: "*.bam"
  - - genomic_ranges:
        type: file
        description: Annotation file in GTF, BED, or VCF format
        pattern: "*.{gtf,bed,vcf}"
output:
  counts:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.tsv":
          type: file
          description: Read counts output file
          pattern: "*.tsv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
